## NumPy Assignments Notebook
This repository contains practical assignments designed to build a strong foundation in NumPy, a fundamental Python library for numerical computing.
Each assignment covers essential NumPy operations with **clear use cases** that align with real-world data processing and analysis tasks.

---
# Overview of Assignments and Use Cases

##1. Array Creation and Manipulation
Create and modify arrays with random or sequential data.

Use Case: Initializing datasets or matrices and updating specific rows or columns for data cleaning or feature engineering.

##2. Array Indexing and Slicing
Extract sub-arrays or specific sections using slicing techniques.

Use Case: Cropping images, selecting data subsets, or isolating features for focused analysis.

##3. Array Operations
Perform element-wise arithmetic operations and compute row/column-wise aggregates.

Use Case: Quick vectorized calculations like combining datasets, calculating totals, or preparing data for machine learning.

##4. Statistical Operations
Calculate mean, median, variance, and standard deviation, and normalize data arrays.

Use Case: Data summarization, feature scaling, and preparation for statistical modeling.

##5. Broadcasting
Apply operations between arrays of different shapes efficiently.

Use Case: Add or subtract vectors from matrices for batch data transformations without explicit loops.

##6. Linear Algebra
Compute determinants, inverses, eigenvalues, and perform matrix multiplication.

Use Case: Solving systems of equations, data transformations, and principal component analysis.

##7. Advanced Array Manipulation
Reshape and flatten arrays to adapt data structure for different processing needs.

Use Case: Preparing image data for neural networks or flattening multi-dimensional data for modeling.

##8. Fancy and Boolean Indexing
Extract elements using specific indices or conditional logic.

Use Case: Select special elements like corners or cap values based on thresholds for data cleaning.

##9. Structured Arrays
Work with arrays containing mixed data types and sort or compute distances.

Use Case: Manage tabular data with heterogeneous columns or perform spatial calculations.

##10. Masked Arrays
Handle arrays with invalid or missing data by masking elements.

Use Case: Ignore outliers or missing data during calculations without deleting entire datasets.

---
Each assignment contains clear examples and code demonstrations to help master Numpy for real-world data tasks.

##Assignment 1: Array Creation and Manipulation
####Assignment 1.1
**Create** a NumPy array of shape (5, 5) filled with **random integers** between 1 and 20. Replace all elements in the third column with 1.

---
**E (Engineering Intuition):**
- Use `np.random.randint` to generate the initial array.
- Use slicing to select the third column `array[:, 2]` (all rows, column index 2).
- Assign 1 to all selected elements.

**L (Lifecycle Use Case):**
- **Data preprocessing**: replacing or masking a specific feature column in a dataset.
- **Quick edits** in matrices or grids.

**L (Limitations & Strategy)**:
- Ensure correct column index (Python indexing starts at 0).

In [2]:
import numpy as np
# Create random array
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace 3rd column with 1
array[:, 2] = 1
print("\nModified array (third column set to 1):")
print(array)


Original array:
[[17 12 19  7  2]
 [ 3 20  5 14 18]
 [ 2  1 13  8  2]
 [ 7 17 15 13 19]
 [10 19  8  5 19]]

Modified array (third column set to 1):
[[17 12  1  7  2]
 [ 3 20  1 14 18]
 [ 2  1  1  8  2]
 [ 7 17  1 13 19]
 [10 19  1  5 19]]


###Assignment 1.2:
**Create a NumPy array** of shape (4, 4) with values from 1 to 16.
**Replace the diagonal elements** with 0.

---
E:
- Use `np.arange` and `reshape` to create a sequential matrix.
- Use `np.fill_diagonal` to modify diagonal elements.

L:
- Masking or nullifying diagonal in covariance or adjacency matrices.
- Clearing values for specific positional masking.

L:
- Works only on square matrices.





In [4]:
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

np.fill_diagonal(array, 0)
print("\nModified array (diagonal set to 0):")
print(array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified array (diagonal set to 0):
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


##Assignment 2.1: Array Indexing and Slicing
Extract sub-array from (6, 6) array rows 3-5 and cols 2-4

---
C: Selecting a **sub-table or slice from a big grid** — extracting a small window.

E: Use `slicing array[2:5, 1:4]` (Python indexing: rows 2 to 4 inclusive, cols 1 to 3 inclusive).

L: Useful for cropping images or **selecting features**.

L: **Slicing creates a view**, not copy. **Modifications affect original.**

In [5]:
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

sub_array = array[2:5, 1:4]
print("\nSub-array (rows 3-5, cols 2-4):")
print(sub_array)


Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array (rows 3-5, cols 2-4):
[[14 15 16]
 [20 21 22]
 [26 27 28]]


## Assignment 2.2: Extract border elements

C: Imagine peeling the outermost layer of a grid — all edge elements.

E: Combine top row, bottom row, left column (excluding corners already taken), and right column.

L: **Border extraction in image processing or matrix boundary checks**.

L: Careful to avoid duplicating corners when concatenating.


In [6]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

border_elements = np.concatenate((
    array[0, :],          # top row
    array[-1, :],         # bottom row
    array[1:-1, 0],       # left column middle rows
    array[1:-1, -1]       # right column middle rows
))
print("\nBorder elements:")
print(border_elements)


Original array:
[[19  1 16 10 13]
 [ 7  7 19 16 12]
 [ 3 12 13  9  8]
 [16  8 14  7 14]
 [20  1  9 12 20]]

Border elements:
[19  1 16 10 13 20  1  9 12 20  7  3 16 12  8 14]


## Assignment 3.1: Element-wise operations between two arrays
C: **adding or multiplying** two grids cell-by-cell.

E: Use +, -, *, / operators for element-wise operations on same shape arrays.

L: Used in **vectorized calculations in ML** or numerical simulations.

L: **Division can cause errors if denominator has zero**.

In [7]:
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

print("\nAddition:")
print(array1 + array2)
print("Subtraction:")
print(array1 - array2)
print("Multiplication:")
print(array1 * array2)
print("Division:")
print(array1 / array2)


Array 1:
[[ 9 10  2  1]
 [ 1  1  5  1]
 [ 7  1  9 10]]
Array 2:
[[ 2  6  5  6]
 [ 1  3  3  6]
 [ 3  1  1 10]]

Addition:
[[11 16  7  7]
 [ 2  4  8  7]
 [10  2 10 20]]
Subtraction:
[[ 7  4 -3 -5]
 [ 0 -2  2 -5]
 [ 4  0  8  0]]
Multiplication:
[[ 18  60  10   6]
 [  1   3  15   6]
 [ 21   1   9 100]]
Division:
[[4.5        1.66666667 0.4        0.16666667]
 [1.         0.33333333 1.66666667 0.16666667]
 [2.33333333 1.         9.         1.        ]]


## Assignment 3.2: Row-wise and column-wise sum
C: Summing all values in rows or columns like summarizing each feature or sample.

E: Use `np.sum(array, axis=1)` for rows,`axis=0` for columns.

L: Common for **aggregating data statistics**.

L: **Summation reduces dimensionality**.


In [8]:
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("\nRow-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


##Assignment 4.1: Statistical operations
C: Calculate key statistics (mean, median, std, var) summarizing data spread and center.

E: Use `np.mean`, `np.median`, `np.std`, `np.var`.

L: Used in **data analysis** for feature scaling, outlier detection.

L: Can be influenced by **outliers**.

In [9]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

print("\nMean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))
print("Variance:", np.var(array))


Original array:
[[ 6 19  5  2 12]
 [10 11 13 14 10]
 [10  2 11  7  4]
 [ 1  9 20 15 20]
 [12  5  5  7 20]]

Mean: 10.0
Median: 10.0
Standard Deviation: 5.642694391866354
Variance: 31.84


### Assignment 4.2: Normalize array
C: Shift data so it has mean=0, std=1 (standardization).

E: `(array - mean) / std_dev`

L: Preprocessing for **ML algorithms sensitive to scale.**

L: Assumes **normal-like distribution**.

In [10]:
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("\nNormalized array:")
print(normalized_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


###Assignment 5.1: Broadcasting - add 1D array to each row of 2D array
C:**Add a vector** to each row of a matrix without explicit loop.

E: NumPy broadcasts smaller array along matching dimensions.

L: Enables concise, efficient vectorized code.

L: Shapes must be compatible for broadcasting.

In [11]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

result = array + row_array  # Broadcast row_array to rows
print("\nResulting array:")
print(result)


Original array:
[[ 7  7  6]
 [ 1  5 10]
 [ 6  8 10]]
1D array:
[ 1  8 10]

Resulting array:
[[ 8 15 16]
 [ 2 13 20]
 [ 7 16 20]]


###Assignment 5.2: Broadcasting - subtract 1D array from each column
C: Subtract a vector from each column by broadcasting.

E: Use `column_array[:, np.newaxis]` to reshape for broadcasting.

L: Useful in **column-wise feature normalization**.

L: Must **reshape correctly to avoid errors**.

In [12]:
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

result = array - column_array[:, np.newaxis]
print("\nResulting array:")
print(result)


Original array:
[[10  6  9  7]
 [ 3  3  8  5]
 [ 8 10  4  1]
 [ 3  4  2  8]]
1D array:
[1 4 3 1]

Resulting array:
[[ 9  5  8  6]
 [-1 -1  4  1]
 [ 5  7  1 -2]
 [ 2  3  1  7]]


###Assignment 6.1: Linear algebra - determinant, inverse, eigenvalues
C: Compute matrix properties: determinant (scale factor), inverse (undo matrix), eigenvalues (inherent modes).

E: Use `np.linalg.det`, `np.linalg.inv`, `np.linalg.eigvals`.

L: Important for **solving linear systems, stability analysis**.

L: **Inverse exists only if determinant ≠ 0**.

In [13]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

determinant = np.linalg.det(matrix)
print("\nDeterminant:", determinant)

if determinant != 0:
    inverse = np.linalg.inv(matrix)
    print("Inverse:")
    print(inverse)
else:
    print("Matrix is singular and cannot be inverted.")

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:")
print(eigenvalues)


Original matrix:
[[ 5  4 10]
 [10 10  8]
 [ 9  6  2]]

Determinant: -232.0000000000002
Inverse:
[[ 0.12068966 -0.22413793  0.29310345]
 [-0.22413793  0.34482759 -0.25862069]
 [ 0.12931034 -0.02586207 -0.04310345]]
Eigenvalues:
[21.1200304  -5.96238567  1.84235527]


###Assignment 6.2: Matrix multiplication
C: Multiply two compatible matrices, producing a new matrix combining rows and columns.

E: Use `np.dot()`.

L: Core operation in **ML, graphics, physics**.

L: Shape must be compatible **(inner dimensions equal)**.

In [14]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

result = np.dot(array1, array2)
print("\nMatrix multiplication result:")
print(result)


Array 1:
[[3 2 3]
 [1 9 7]]
Array 2:
[[ 9  1]
 [ 1  7]
 [ 2 10]]

Matrix multiplication result:
[[ 35  47]
 [ 32 134]]


###Assignment 7.1: Reshape array
C: Change the shape of the array without changing data.

E: Use `.reshape()`.

L: Useful in **preparing data for ML models, flattening images**.

L: Total elements must remain **constant**.

In [15]:
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

reshaped_1 = array.reshape((1, 9))
print("\nReshaped array (1, 9):")
print(reshaped_1)

reshaped_2 = reshaped_1.reshape((9, 1))
print("\nReshaped array (9, 1):")
print(reshaped_2)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]

Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## Assignment 7.2: Flatten and reshape back
C: Flatten to 1D then revert to original shape.

E: Use `.flatten()` and `.reshape()`.

L: Common in **image processing pipelines**.

L: Flatten returns a copy.

In [16]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

flattened = array.flatten()
print("\nFlattened array:")
print(flattened)

reshaped = flattened.reshape((5, 5))
print("\nReshaped array:")
print(reshaped)


Original array:
[[19  2 10  2  9]
 [ 6  2  7 14  3]
 [ 3  1 11  9 16]
 [15 20  7 20 12]
 [11 18 15  4 16]]

Flattened array:
[19  2 10  2  9  6  2  7 14  3  3  1 11  9 16 15 20  7 20 12 11 18 15  4
 16]

Reshaped array:
[[19  2 10  2  9]
 [ 6  2  7 14  3]
 [ 3  1 11  9 16]
 [15 20  7 20 12]
 [11 18 15  4 16]]


###Assignment 8.1: Fancy indexing - corners extraction
C: Select specific elements by row and column indices.

E: Use arrays of **indices for rows and columns**.

L: Accessing s**pecial positions (corners, edges**).

L: Index arrays must be same length.

In [17]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("\nCorner elements:")
print(corners)


Original array:
[[11  5  5 12 20]
 [11  5  7 19  5]
 [ 5 11  1  8  2]
 [ 7  8 12  1 15]
 [ 9 17 10 20 12]]

Corner elements:
[11 20  9 12]


###Assignment 8.2: Boolean indexing - cap elements
C: Select elements based on condition and modify.

E: Use boolean mask `array > 10` to set ***all >10*** to 10.

L: Data cleaning, clipping **outliers**.

L: Works on mutable arrays.

In [18]:
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

array[array > 10] = 10
print("\nModified array (values > 10 set to 10):")
print(array)


Original array:
[[ 2  6 13  5]
 [19  3  5 12]
 [15  9 11 16]
 [ 2 17 20 14]]

Modified array (values > 10 set to 10):
[[ 2  6 10  5]
 [10  3  5 10]
 [10  9 10 10]
 [ 2 10 10 10]]


## Assignment 9.1: Structured arrays - sort by age
C: Array with multiple named fields (like a small database).

E: Define **dtype, create array, sort by field.**

L: Handling **mixed data types**, structured records.

L: Sorting only by one field at a time.

In [20]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("\nSorted array by age:")
print(sorted_data)


Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]

Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


## Assignment 9.2: Structured arrays - Euclidean distance
C: Points with coordinates; compute distances pairwise.

E: Use broadcasting and **square root of sum of squares**.

L: Spatial calculations, clustering.

L: Works only with **numeric fields**.

In [21]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

distances = np.sqrt((data['x'][:, None] - data['x'])**2 + (data['y'][:, None] - data['y'])**2)
print("\nEuclidean distances:")
print(distances)


Original array:
[(1, 2) (3, 4) (5, 6)]

Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10.1: Masked arrays - mask elements > 10 and sum unmasked
C: **Mask array elements based on condition and operate only on visible ones**.

E: Use `np.ma.masked_greater`.

L: Handling missing or invalid data.

L: Masked **operations may be slower**.

In [23]:
import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("\nMasked array (elements > 10 masked):")
print(masked_array)

sum_unmasked = masked_array.sum()
print("\nSum of unmasked elements:", sum_unmasked)


Original array:
[[ 3 17  6 12]
 [ 2  7  8  1]
 [ 8 17 20 11]
 [14  6 11 15]]

Masked array (elements > 10 masked):
[[3 -- 6 --]
 [2 7 8 1]
 [8 -- -- --]
 [-- 6 -- --]]

Sum of unmasked elements: 41


####Assignment 10.2: Mask diagonal, replace masked with mean of unmasked
C: Mask diagonal and fill masked with mean of rest.

E: Use mask with identity matrix, `.filled()` with mean.

L: Data imputation or cleaning.

L: Mask must be boolean with correct shape.


In [24]:
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("\nMasked array (diagonal masked):")
print(masked_array)

mean_unmasked = masked_array.mean()
filled_array = masked_array.filled(mean_unmasked)
print("\nModified masked array (diagonal replaced with mean):")
print(filled_array)


Original array:
[[15 10  4]
 [12  1  6]
 [ 5  6 11]]

Masked array (diagonal masked):
[[-- 10 4]
 [12 -- 6]
 [5 6 --]]

Modified masked array (diagonal replaced with mean):
[[ 7 10  4]
 [12  7  6]
 [ 5  6  7]]


## **Motivation**
Learning NumPy through hands-on assignments builds the foundation for efficient data manipulation, analysis, and scientific computing. This process trains you to think in **arrays and vectorized operations**.



### **Assignments → Use Cases**

1. **Create and modify arrays** → Initialize datasets, change specific values for cleaning or preprocessing.
2. **Indexing and slicing** → Select subsets of data for analysis or modeling.
3. **Element-wise operations** → Perform fast calculations without loops.
4. **Statistical calculations** → Summarize datasets, prepare for analytics.
5. **Broadcasting** → Apply transformations to entire datasets efficiently.
6. **Linear algebra** → Solve equations, transformations, and model computations.
7. **Reshaping and flattening** → Prepare data for ML models or reshape for visualization.
8. **Fancy indexing** → Extract irregular patterns or important points from datasets.
9. **Boolean indexing** → Filter datasets based on conditions.
10. **Structured arrays** → Manage data with mixed types (like a spreadsheet).
11. **Sorting and filtering** → Organize data for analysis or reporting.
12. **Distance computations** → Measure similarity or spatial distances between data points.
13. **Masked arrays** → Work with missing/invalid data without breaking computations.

---

## **Challenges**

* **Remembering NumPy syntax** for different indexing and reshaping operations.
* **Understanding broadcasting rules** when working with arrays of different shapes.
* **Debugging shape mismatches** in operations like matrix multiplication.
* **Interpreting error messages** for advanced functions (like `linalg` methods).
* **Visualizing changes** — hard to imagine transformations without before/after comparisons.
* **Handling missing or invalid data** in masked arrays without losing important information.

---

###Personal takeaway:
Creating this repo was tough!
As an **aspiring Solutions Architect**, I aim to solve complex challenges like this often, using a C.E.L.L method keeps learn simple and efficient.
So Much so I came to realise; I am not **learning code, but patterns**.
Remembering all this information becomes easier using this method, however, situations call for fast-decisive action therefore I began to adapt into spotting **reuseable code**-tutorials, youtube, github repos, etc.
Perhaps this may evolve into 'mental-templates' for long-term recall, if not I still have this repo for my personal Ref.